image: node:24

stages:
  - test
  - build

before_script:
  - npm ci

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/